//! Golden SQL-contract fixtures shared with the explorer.
//!
//! The explorer hard-codes the indexer's SQL contract in TypeScript
//! (`explorer/src/sqlContract.ts`): table and column names, the numeric
//! `tx_activity` role and kind values, and the qmdb facade's routes. Nothing
//! else ties the two sides together, so renaming a column or renumbering a
//! kind would compile on both sides and break the explorer only at runtime.
//! Like the wire fixtures (`crates/primitives/tests/wire_fixtures.rs`), this
//! test makes the Rust constants the source of truth: it asserts the
//! checked-in fixture file matches, and the explorer's test suite asserts its
//! constants against the same file, so drift on either side fails CI.
//!
//! After an intentional contract change, regenerate with:
//!
//! ```text
//! UPDATE_SQL_FIXTURES=1 cargo test -p constantinople-indexer --test sql_fixtures
//! ```

use constantinople_indexer::sql_schema;
use serde_json::json;
use std::path::PathBuf;

fn build_fixture() -> serde_json::Value {
    json!({
        "comment": "Generated by crates/indexer/tests/sql_fixtures.rs — do not edit by hand. \
                    Regenerate with UPDATE_SQL_FIXTURES=1 after an intentional contract change.",
        "qmdbRoutes": {
            "state": constantinople_indexer::QMDB_STATE_ROUTE,
            "transactions": constantinople_indexer::QMDB_TRANSACTIONS_ROUTE,
        },
        "tables": {
            "blockMeta": sql_schema::BLOCK_META_TABLE,
            "txMeta": sql_schema::TX_META_TABLE,
            "txActivity": sql_schema::TX_ACTIVITY_TABLE,
            "accountMeta": sql_schema::ACCOUNT_META_TABLE,
        },
        "columns": {
            "blockMeta": {
                "height": sql_schema::BLOCK_META_HEIGHT,
                "digest": sql_schema::BLOCK_META_DIGEST,
                "txCount": sql_schema::BLOCK_META_TX_COUNT,
                "transfers": sql_schema::BLOCK_META_TRANSFERS,
                "channelOpens": sql_schema::BLOCK_META_CHANNEL_OPENS,
                "channelCloses": sql_schema::BLOCK_META_CHANNEL_CLOSES,
                "channelTimeouts": sql_schema::BLOCK_META_CHANNEL_TIMEOUTS,
                "mints": sql_schema::BLOCK_META_MINTS,
                "transactionsRoot": sql_schema::BLOCK_META_TRANSACTIONS_ROOT,
                "transactionsTip": sql_schema::BLOCK_META_TRANSACTIONS_TIP,
                "view": sql_schema::BLOCK_META_VIEW,
                "finalizedTs": sql_schema::BLOCK_META_FINALIZED_TS,
            },
            "txMeta": {
                "digest": sql_schema::TX_META_DIGEST,
                "qmdbLocation": sql_schema::TX_META_QMDB_LOCATION,
                "bodyHex": sql_schema::TX_META_BODY_HEX,
            },
            "txActivity": {
                "account": sql_schema::TX_ACTIVITY_ACCOUNT,
                "height": sql_schema::TX_ACTIVITY_HEIGHT,
                "index": sql_schema::TX_ACTIVITY_INDEX,
                "role": sql_schema::TX_ACTIVITY_ROLE,
                "digest": sql_schema::TX_ACTIVITY_DIGEST,
                "counterparty": sql_schema::TX_ACTIVITY_COUNTERPARTY,
                "value": sql_schema::TX_ACTIVITY_VALUE,
                "nonce": sql_schema::TX_ACTIVITY_NONCE,
                "kind": sql_schema::TX_ACTIVITY_KIND,
            },
            "accountMeta": {
                "account": sql_schema::ACCOUNT_META_ACCOUNT,
                "balance": sql_schema::ACCOUNT_META_BALANCE,
                "nonceBase": sql_schema::ACCOUNT_META_NONCE_BASE,
                "nonceBitmap": sql_schema::ACCOUNT_META_NONCE_BITMAP,
                "qmdbLocation": sql_schema::ACCOUNT_META_QMDB_LOCATION,
                "deleted": sql_schema::ACCOUNT_META_DELETED,
            },
        },
        "txActivityRoles": {
            "sender": sql_schema::TX_ACTIVITY_ROLE_SENDER,
            "receiver": sql_schema::TX_ACTIVITY_ROLE_RECEIVER,
        },
        "txActivityKinds": {
            "transfer": sql_schema::TX_ACTIVITY_KIND_TRANSFER,
            "channelOpen": sql_schema::TX_ACTIVITY_KIND_CHANNEL_OPEN,
            "channelClose": sql_schema::TX_ACTIVITY_KIND_CHANNEL_CLOSE,
            "channelTimeout": sql_schema::TX_ACTIVITY_KIND_CHANNEL_TIMEOUT,
            "mint": sql_schema::TX_ACTIVITY_KIND_MINT,
        },
    })
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../explorer/tests/fixtures/sql.json")
}

#[test]
fn sql_fixtures_match_the_checked_in_file() {
    let generated = build_fixture();
    let path = fixture_path();

    if std::env::var("UPDATE_SQL_FIXTURES").is_ok() {
        let pretty = serde_json::to_string_pretty(&generated).expect("fixture pretty-prints");
        std::fs::write(&path, pretty + "\n").expect("fixture file writes");
        return;
    }

    let checked_in: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!(
                "missing SQL fixture at {path:?} ({error}); generate it with \
                 UPDATE_SQL_FIXTURES=1 cargo test -p constantinople-indexer --test sql_fixtures"
            )
        }))
        .expect("fixture file parses");

    assert_eq!(
        checked_in, generated,
        "the tx_activity contract no longer matches explorer/tests/fixtures/sql.json; if the \
         change is intentional, regenerate with UPDATE_SQL_FIXTURES=1 and update the explorer \
         constants to match"
    );
}
