{
 "title": "Constantinople",
 "tags": [ "constantinople" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Validator", "query": { "query": "label_values(deployer_name)" } },
   { "name": "Region", "query": { "query": "label_values(deployer_region)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Views Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(engine_simplex_voter_state_current_view[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "engine_simplex_voter_state_current_view",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / avg(irate(engine_simplex_voter_state_current_view[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(engine_application_proposed_transactions_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Marshal Finalized Height",
   "type": "timeseries",
   "description": "Height of the latest finalized block that marshal knows about",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "engine_marshal_finalized_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Marshal Processed Height",
   "type": "timeseries",
   "description": "Height of the latest finalized block that the application has processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "engine_marshal_processed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Block Building Duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(engine_application_build_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Building Duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(engine_application_build_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Building Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_application_build_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Verify Duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(engine_application_verify_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Verify Duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(engine_application_verify_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Verify Duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_application_verify_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erasure Encode Duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(engine_application_erasure_encode_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erasure Encode Duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(engine_application_erasure_encode_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erasure Encode Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_application_erasure_encode_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erasure Decode Duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(engine_shards_erasure_decode_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erasure Decode Duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(engine_shards_erasure_decode_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erasure Decode Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_shards_erasure_decode_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pruned Forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "engine_stateful_pruned_forks_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Batch Size (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "avg by(deployer_name, deployer_ip) (histogram_quantile(0.5, rate(engine_simplex_batcher_batch_size_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batch Size (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "targets": [
    {
     "expr": "avg by(deployer_name, deployer_ip) (histogram_quantile(0.9, rate(engine_simplex_batcher_batch_size_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batchable Messages Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "irate(engine_simplex_batcher_added_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batch Verifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "targets": [
    {
     "expr": "irate(engine_simplex_batcher_batch_size_count{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batch Verify Latency (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(engine_simplex_batcher_verify_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval]))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Recover Latency (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(engine_simplex_batcher_recover_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval]))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Notarization Latency (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(engine_simplex_voter_notarization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Finalization Latency (p75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(engine_simplex_voter_finalization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Sync Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_stateful_state_sync_state_sync_done",
     "legendFormat": "{{deployer_ip}}"
    }
   ]
  },
  {
   "title": "State Sync Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "engine_stateful_state_sync_sync_target_end",
     "legendFormat": "DB {{db}} Target Operations"
    },
    {
     "expr": "engine_stateful_state_sync_sync_journal_size",
     "legendFormat": "DB {{db}} Journal Size"
    }
   ]
  },
  {
   "title": "State Sync Target Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "engine_stateful_state_sync_sync_target_height",
     "legendFormat": "DB {{db}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Inbound Bandwidth per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(runtime_inbound_bandwidth_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(runtime_outbound_bandwidth_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Dial Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "expr": "sum by(deployer_name, deployer_ip) (p2p_dialer_attempts_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"})",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "p2p_tracker_directory_tracked{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 109 },
   "targets": [
    {
     "expr": "count by(deployer_name, deployer_ip) (p2p_tracker_directory_connected{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"})",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Peer Average Connection Age",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by(peer) (clamp_min((time() * 1000 - p2p_tracker_directory_connected{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}) / 1000, 0)))",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Peers Blocked",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "p2p_tracker_directory_blocked_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Disk Writes per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Disk Reads per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 128 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Cached Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Open Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 128 },
   "targets": [
    { "expr": "runtime_open_blobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\", mountpoint=\"/\"} - node_filesystem_free_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\", mountpoint=\"/\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "targets": [
    { "expr": "runtime_tasks_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Spawned Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "targets": [
    { "expr": "runtime_tasks_spawned_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} - node_memory_MemFree_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} - node_memory_Buffers_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} - node_memory_Cached_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 164 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployer_arch=\"arm64\"} | json"
    }
   ]
  },
  {
   "title": "Spammer Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 174 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployer_name=\"spammer\"}"
    }
   ]
  }
 ]
}