# Mount Constantinople plus its sibling Exoware checkout. Cargo resolves
# `../exoware-monorepo-faster-qmdb-uploads` from `/constantinople` to
# `/exoware-monorepo-faster-qmdb-uploads` inside the builder container.
source-mounts := "-v ${PWD}:/constantinople -v ${PWD}/../exoware-monorepo-faster-qmdb-uploads:/exoware-monorepo-faster-qmdb-uploads:ro"

# Build the Graviton Docker builder image
build-graviton-image:
  docker buildx bake --progress plain -f docker/docker-bake.hcl graviton

# Build the ARM64 validator binary into deploy/
validator-graviton-binary: build-graviton-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-validator \
    -e BINARY_NAME=constantinople \
    -e OUTPUT_NAME=validator \
    constantinople-builder:graviton-local

# Build the ARM64 spammer binary into deploy/
spammer-graviton-binary: build-graviton-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-spammer \
    -e BINARY_NAME=constantinople-spammer \
    -e OUTPUT_NAME=spammer \
    constantinople-builder:graviton-local

# Build the ARM64 chain-indexer binary into deploy/
chain-indexer-graviton-binary: build-graviton-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-indexer \
    -e BINARY_NAME=chain-indexer \
    -e OUTPUT_NAME=chain-indexer \
    constantinople-builder:graviton-local

# Build the ARM64 metadata-indexer binary into deploy/
metadata-indexer-graviton-binary: build-graviton-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-indexer \
    -e BINARY_NAME=metadata-indexer \
    -e OUTPUT_NAME=metadata-indexer \
    constantinople-builder:graviton-local

# Build the ARM64 qmdb-indexer binary into deploy/
qmdb-indexer-graviton-binary: build-graviton-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-indexer \
    -e BINARY_NAME=qmdb-indexer \
    -e OUTPUT_NAME=qmdb-indexer \
    constantinople-builder:graviton-local

# Build all ARM64 binaries into deploy/
graviton-binaries: validator-graviton-binary spammer-graviton-binary chain-indexer-graviton-binary metadata-indexer-graviton-binary qmdb-indexer-graviton-binary

# Build the Intel/C8i Docker builder image
build-intel-image:
  docker buildx bake --progress plain -f docker/docker-bake.hcl intel

# Build the Intel validator binary into deploy/
validator-intel-binary: build-intel-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-validator \
    -e BINARY_NAME=constantinople \
    -e OUTPUT_NAME=validator \
    constantinople-builder:intel-local

# Build the Intel spammer binary into deploy/
spammer-intel-binary: build-intel-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-spammer \
    -e BINARY_NAME=constantinople-spammer \
    -e OUTPUT_NAME=spammer \
    constantinople-builder:intel-local

# Build the Intel chain-indexer binary into deploy/
chain-indexer-intel-binary: build-intel-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-indexer \
    -e BINARY_NAME=chain-indexer \
    -e OUTPUT_NAME=chain-indexer \
    constantinople-builder:intel-local

# Build the Intel metadata-indexer binary into deploy/
metadata-indexer-intel-binary: build-intel-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-indexer \
    -e BINARY_NAME=metadata-indexer \
    -e OUTPUT_NAME=metadata-indexer \
    constantinople-builder:intel-local

# Build the Intel qmdb-indexer binary into deploy/
qmdb-indexer-intel-binary: build-intel-image
  docker run --rm {{source-mounts}} \
    -e PACKAGE_NAME=constantinople-indexer \
    -e BINARY_NAME=qmdb-indexer \
    -e OUTPUT_NAME=qmdb-indexer \
    constantinople-builder:intel-local

# Build all Intel binaries into deploy/
intel-binaries: validator-intel-binary spammer-intel-binary chain-indexer-intel-binary metadata-indexer-intel-binary qmdb-indexer-intel-binary
