import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

import {
    ACCOUNT_META_ACCOUNT,
    ACCOUNT_META_DELETED,
    BLOCK_META_CHANNEL_CLOSES,
    BLOCK_META_CHANNEL_OPENS,
    BLOCK_META_CHANNEL_TIMEOUTS,
    BLOCK_META_MINTS,
    BLOCK_META_TRANSFERS,
    ACCOUNT_META_BALANCE,
    ACCOUNT_META_NONCE_BASE,
    ACCOUNT_META_NONCE_BITMAP,
    ACCOUNT_META_QMDB_LOCATION,
    ACCOUNT_META_TABLE,
    BLOCK_META_DIGEST,
    BLOCK_META_HEIGHT,
    BLOCK_META_TABLE,
    BLOCK_META_TX_COUNT,
    QMDB_STATE_ROUTE,
    QMDB_TRANSACTIONS_ROUTE,
    TX_ACTIVITY_ACCOUNT,
    TX_ACTIVITY_COUNTERPARTY,
    TX_ACTIVITY_DIGEST,
    TX_ACTIVITY_HEIGHT,
    TX_ACTIVITY_INDEX,
    TX_ACTIVITY_KIND,
    TX_ACTIVITY_KINDS,
    TX_ACTIVITY_NONCE,
    TX_ACTIVITY_ROLE,
    TX_ACTIVITY_ROLES,
    TX_ACTIVITY_TABLE,
    TX_ACTIVITY_VALUE,
    TX_META_BODY_HEX,
    TX_META_DIGEST,
    TX_META_QMDB_LOCATION,
    TX_META_TABLE,
} from '../src/sqlContract.ts';

// Golden fixtures generated by the indexer's SQL contract
// (crates/indexer/tests/sql_fixtures.rs). The Rust test asserts the file
// matches its constants; this test asserts the explorer's copy of the
// contract agrees with the file, so renaming a table/column or renumbering a
// role/kind on either side fails CI instead of breaking explorer queries at
// runtime.
interface SqlFixture {
    readonly qmdbRoutes: { readonly [name: string]: string };
    readonly tables: { readonly [name: string]: string };
    readonly columns: { readonly [table: string]: { readonly [name: string]: string } };
    readonly txActivityRoles: { readonly [name: string]: number };
    readonly txActivityKinds: { readonly [name: string]: number };
}

// Tests compile to dist-test/ before running, so resolve the fixture from
// the package root (npm test's working directory), not the compiled file.
const fixture: SqlFixture = JSON.parse(
    readFileSync(join(process.cwd(), 'tests', 'fixtures', 'sql.json'), 'utf8'),
);

// The fixture's shape, grouped from the contract constants the production
// code imports, so the comparisons below reference each name exactly once.
const tables = {
    blockMeta: BLOCK_META_TABLE,
    txMeta: TX_META_TABLE,
    txActivity: TX_ACTIVITY_TABLE,
    accountMeta: ACCOUNT_META_TABLE,
};
const columns: { [table: string]: { [name: string]: string } } = {
    blockMeta: {
        height: BLOCK_META_HEIGHT,
        digest: BLOCK_META_DIGEST,
        txCount: BLOCK_META_TX_COUNT,
        transfers: BLOCK_META_TRANSFERS,
        channelOpens: BLOCK_META_CHANNEL_OPENS,
        channelCloses: BLOCK_META_CHANNEL_CLOSES,
        channelTimeouts: BLOCK_META_CHANNEL_TIMEOUTS,
        mints: BLOCK_META_MINTS,
    },
    txMeta: {
        digest: TX_META_DIGEST,
        qmdbLocation: TX_META_QMDB_LOCATION,
        bodyHex: TX_META_BODY_HEX,
    },
    txActivity: {
        account: TX_ACTIVITY_ACCOUNT,
        height: TX_ACTIVITY_HEIGHT,
        index: TX_ACTIVITY_INDEX,
        role: TX_ACTIVITY_ROLE,
        digest: TX_ACTIVITY_DIGEST,
        counterparty: TX_ACTIVITY_COUNTERPARTY,
        value: TX_ACTIVITY_VALUE,
        nonce: TX_ACTIVITY_NONCE,
        kind: TX_ACTIVITY_KIND,
    },
    accountMeta: {
        account: ACCOUNT_META_ACCOUNT,
        balance: ACCOUNT_META_BALANCE,
        nonceBase: ACCOUNT_META_NONCE_BASE,
        nonceBitmap: ACCOUNT_META_NONCE_BITMAP,
        qmdbLocation: ACCOUNT_META_QMDB_LOCATION,
        deleted: ACCOUNT_META_DELETED,
    },
};

function asBigInts(values: { readonly [name: string]: number }): { [name: string]: bigint } {
    return Object.fromEntries(Object.entries(values).map(([name, value]) => [name, BigInt(value)]));
}

test('qmdb facade routes match the indexer contract', () => {
    assert.deepEqual(
        { state: QMDB_STATE_ROUTE, transactions: QMDB_TRANSACTIONS_ROUTE },
        fixture.qmdbRoutes,
    );
});

test('table names match the indexer contract', () => {
    assert.deepEqual(tables, fixture.tables);
});

test('column names match the indexer contract', () => {
    // The explorer reads a subset of some tables' columns, so every column it
    // declares must match the fixture; the fixture may carry more.
    for (const [table, declared] of Object.entries(columns)) {
        const expected = fixture.columns[table];
        assert.ok(expected, `fixture covers the ${table} table`);
        for (const [name, value] of Object.entries(declared)) {
            assert.equal(value, expected[name], `${table}.${name}`);
        }
    }
});

test('tx_activity roles and kinds match the indexer contract', () => {
    assert.deepEqual({ ...TX_ACTIVITY_ROLES }, asBigInts(fixture.txActivityRoles));
    assert.deepEqual({ ...TX_ACTIVITY_KINDS }, asBigInts(fixture.txActivityKinds));
});
