import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

import { webcrypto } from 'node:crypto';

import {
    MAX_MINT_AMOUNT,
    TRANSACTION_NAMESPACE,
    VOUCHER_NAMESPACE,
    channelAddress,
    ed25519TransactionSignature,
    encodeSignedMintTransaction,
    encodeSignedOpenChannelTransaction,
    encodeSignedTimeoutChannelTransaction,
    encodeSignedTransaction,
    encodeTransactionBatch,
    fromHex,
    signedTransactionBodyLength,
    toHex,
    unionUnique,
    voucherSigningPayload,
} from '../src/codec.ts';
import {
    STREAM_CHUNK_EVENT,
    STREAM_END_EVENT,
    STREAM_END_REASONS,
    STREAM_PAYMENT_REQUIRED_EVENT,
    parseStreamChunk,
    parseStreamEnd,
    registerRequestBody,
    settleRequestBody,
    voucherRequestBody,
} from '../src/paidStream.ts';

// Golden fixtures generated by the Rust codec
// (crates/primitives/tests/wire_fixtures.rs). The Rust test asserts the file
// matches its codec; these tests assert this codec agrees with the file, so
// wire-format drift on either side fails CI instead of a browser session.
interface TransactionFixture {
    readonly kind: string;
    readonly signedHex: string;
    readonly bodyLength: number;
    readonly digestHex: string;
    readonly senderPublicKeyHex: string;
    readonly nonce: string;
    readonly toAccountKeyHex?: string;
    readonly value?: string;
    readonly receiverAccountKeyHex?: string;
    readonly operatorAccountKeyHex?: string;
    readonly deposit?: string;
    readonly expiry?: string;
}

interface ChannelFixture {
    readonly payerPrivateKeyHex: string;
    readonly payerAccountHex: string;
    readonly receiverAccountHex: string;
    readonly operatorAccountHex: string;
    readonly voucherPrivateKeyHex: string;
    readonly voucherPublicKeyHex: string;
    readonly openNonce: string;
    readonly addressHex: string;
    readonly transactionNamespace: string;
    readonly voucherNamespace: string;
    readonly voucherCumulative: string;
    readonly voucherMessageHex: string;
    readonly voucherSignatureHex: string;
    readonly zeroVoucherSignatureHex: string;
}

interface StreamFixture {
    readonly chunkEvent: string;
    readonly paymentRequiredEvent: string;
    readonly endEvent: string;
    readonly endReasons: readonly string[];
    readonly chunkSample: string;
    readonly endSample: string;
}

interface RequestFixture {
    readonly registerSample: string;
    readonly voucherSample: string;
    readonly settleSample: string;
}

interface WireFixture {
    readonly maxMintAmount: string;
    readonly batchHex: string;
    readonly transactions: readonly TransactionFixture[];
    readonly channel: ChannelFixture;
    readonly stream: StreamFixture;
    readonly requests: RequestFixture;
}

// Tests compile to dist-test/ before running, so resolve the fixture from
// the package root (npm test's working directory), not the compiled file.
const fixture: WireFixture = JSON.parse(
    readFileSync(join(process.cwd(), 'tests', 'fixtures', 'wire.json'), 'utf8'),
);

function entry(kind: string): TransactionFixture {
    const found = fixture.transactions.find((tx) => tx.kind === kind);
    assert.ok(found, `fixture covers a ${kind}`);
    return found;
}

// The scheme-tagged signature tail, for injecting into an encoder whose real
// signer is WebAuthn.
function signatureOf(tx: TransactionFixture): Uint8Array {
    return fromHex(tx.signedHex).slice(tx.bodyLength);
}

test('mint cap matches the Rust codec', () => {
    assert.equal(MAX_MINT_AMOUNT, BigInt(fixture.maxMintAmount));
});

test('every operation kind is present and its body length agrees', () => {
    assert.deepEqual(
        fixture.transactions.map((tx) => tx.kind).sort(),
        ['close_channel', 'mint', 'open_channel', 'timeout_channel', 'transfer'],
    );
    for (const tx of fixture.transactions) {
        assert.equal(
            signedTransactionBodyLength(fromHex(tx.signedHex)),
            tx.bodyLength,
            `${tx.kind} body length`,
        );
    }
});

test('transfer encoding is byte-identical to the Rust codec', async () => {
    const tx = entry('transfer');
    const encoded = await encodeSignedTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            toAccountKey: fromHex(tx.toAccountKeyHex ?? ''),
            value: BigInt(tx.value ?? ''),
            nonce: BigInt(tx.nonce),
        },
        async () => signatureOf(tx),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
    assert.equal(encoded.digestHex, tx.digestHex);
});

test('mint encoding is byte-identical to the Rust codec', async () => {
    const tx = entry('mint');
    const encoded = await encodeSignedMintTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            amount: BigInt(tx.value ?? ''),
            nonce: BigInt(tx.nonce),
        },
        async () => signatureOf(tx),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
    assert.equal(encoded.digestHex, tx.digestHex);
});

test('batch encoding is byte-identical to the Rust codec', () => {
    const batch = encodeTransactionBatch(
        fixture.transactions.map((tx) => fromHex(tx.signedHex)),
    );
    assert.equal(toHex(batch), fixture.batchHex);
});

test('open channel encoding is byte-identical to the Rust codec', async () => {
    const tx = entry('open_channel');
    const encoded = await encodeSignedOpenChannelTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            receiverAccountKey: fromHex(tx.receiverAccountKeyHex ?? ''),
            operatorAccountKey: fromHex(tx.operatorAccountKeyHex ?? ''),
            voucherPublicKey: fromHex(fixture.channel.voucherPublicKeyHex),
            deposit: BigInt(tx.deposit ?? ''),
            expiry: BigInt(tx.expiry ?? ''),
            nonce: BigInt(tx.nonce),
        },
        async () => signatureOf(tx),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
    assert.equal(encoded.digestHex, tx.digestHex);
});

test('timeout channel encoding is byte-identical to the Rust codec', async () => {
    // The timeout reclaims the channel fixture's escrow, so its receiver,
    // operator, and open nonce come from the channel fixture.
    const tx = entry('timeout_channel');
    const channel = fixture.channel;
    const encoded = await encodeSignedTimeoutChannelTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            receiverAccountKey: fromHex(channel.receiverAccountHex),
            operatorAccountKey: fromHex(channel.operatorAccountHex),
            voucherPublicKey: fromHex(channel.voucherPublicKeyHex),
            openNonce: BigInt(channel.openNonce),
            nonce: BigInt(tx.nonce),
        },
        async () => signatureOf(tx),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
    assert.equal(encoded.digestHex, tx.digestHex);
});

test('channel address derivation matches the Rust codec', async () => {
    const channel = fixture.channel;
    const address = await channelAddress(
        fromHex(channel.payerAccountHex),
        fromHex(channel.receiverAccountHex),
        fromHex(channel.operatorAccountHex),
        fromHex(channel.voucherPublicKeyHex),
        BigInt(channel.openNonce),
    );
    assert.equal(toHex(address), channel.addressHex);
});

test('namespaces match the Rust codec', () => {
    assert.equal(TRANSACTION_NAMESPACE, fixture.channel.transactionNamespace);
    assert.equal(VOUCHER_NAMESPACE, fixture.channel.voucherNamespace);
});

test('stream SSE contract matches the Rust wire types', () => {
    assert.equal(STREAM_CHUNK_EVENT, fixture.stream.chunkEvent);
    assert.equal(STREAM_PAYMENT_REQUIRED_EVENT, fixture.stream.paymentRequiredEvent);
    assert.equal(STREAM_END_EVENT, fixture.stream.endEvent);
    assert.deepEqual([...STREAM_END_REASONS].sort(), [...fixture.stream.endReasons].sort());

    // The samples pin the payload field names end to end: the parsers must
    // accept exactly what serde emits.
    assert.deepEqual(parseStreamChunk(fixture.stream.chunkSample), {
        text: 'hello ',
        served: 1n,
        paid: 0n,
    });
    assert.deepEqual(parseStreamEnd(fixture.stream.endSample), {
        reason: 'payment_timeout',
        served: 32n,
        paid: 7n,
    });
});

test('operator request bodies match the Rust wire types', () => {
    // The request half of the operator contract: what the browser builds
    // must deserialize into RegisterRequest/VoucherRequest/SettleRequest.
    const open = entry('open_channel');
    const channel = fixture.channel;
    assert.deepEqual(
        JSON.parse(
            registerRequestBody({
                openTxDigestHex: open.digestHex,
                zeroVoucherSignatureHex: channel.zeroVoucherSignatureHex,
            }),
        ),
        JSON.parse(fixture.requests.registerSample),
    );
    assert.deepEqual(
        JSON.parse(
            voucherRequestBody({
                channelHex: channel.addressHex,
                cumulative: BigInt(channel.voucherCumulative),
                signatureHex: channel.voucherSignatureHex,
            }),
        ),
        JSON.parse(fixture.requests.voucherSample),
    );
    assert.deepEqual(
        JSON.parse(settleRequestBody(channel.addressHex)),
        JSON.parse(fixture.requests.settleSample),
    );
});

// The fixture carries the payer's and the voucher key's raw ed25519 seeds,
// so both in-browser signing paths — namespace framing included — can be
// exercised end to end: ed25519 is deterministic, so re-signing must
// reproduce the fixture bytes exactly. This is the test that catches
// "signed the wrong bytes" mistakes a correct-looking encoder byte-compare
// cannot.
async function importFixtureKey(seedHex: string): Promise<CryptoKey> {
    // Wrap the raw 32-byte seed in the fixed PKCS8 Ed25519 envelope.
    const pkcs8Prefix = fromHex('302e020100300506032b657004220420');
    const seed = fromHex(seedHex);
    const pkcs8 = new Uint8Array([...pkcs8Prefix, ...seed]);
    return webcrypto.subtle.importKey('pkcs8', pkcs8, 'Ed25519', false, ['sign']);
}

test('voucher signing reproduces the Rust signature byte-for-byte', async () => {
    const channel = fixture.channel;
    const payload = voucherSigningPayload(
        fromHex(channel.addressHex),
        BigInt(channel.voucherCumulative),
    );
    // The payload embeds the fixture's pre-namespace message verbatim.
    assert.ok(toHex(payload).endsWith(channel.voucherMessageHex));

    const key = await importFixtureKey(channel.voucherPrivateKeyHex);
    const signature = new Uint8Array(await webcrypto.subtle.sign('Ed25519', key, payload));
    assert.equal(toHex(signature), channel.voucherSignatureHex);

    // The zero voucher registration carries signs (channel, 0) with the
    // same key.
    const zeroPayload = voucherSigningPayload(fromHex(channel.addressHex), 0n);
    const zeroSignature = new Uint8Array(
        await webcrypto.subtle.sign('Ed25519', key, zeroPayload),
    );
    assert.equal(toHex(zeroSignature), channel.zeroVoucherSignatureHex);
});

test('ed25519 transaction signing reproduces the Rust signature byte-for-byte', async () => {
    const tx = entry('open_channel');
    const key = await importFixtureKey(fixture.channel.payerPrivateKeyHex);
    const encoded = await encodeSignedOpenChannelTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            receiverAccountKey: fromHex(tx.receiverAccountKeyHex ?? ''),
            operatorAccountKey: fromHex(tx.operatorAccountKeyHex ?? ''),
            voucherPublicKey: fromHex(fixture.channel.voucherPublicKeyHex),
            deposit: BigInt(tx.deposit ?? ''),
            expiry: BigInt(tx.expiry ?? ''),
            nonce: BigInt(tx.nonce),
        },
        async (digest) =>
            ed25519TransactionSignature(
                new Uint8Array(
                    await webcrypto.subtle.sign(
                        'Ed25519',
                        key,
                        unionUnique(TRANSACTION_NAMESPACE, digest),
                    ),
                ),
            ),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
});
