import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

import {
    MAX_MINT_AMOUNT,
    encodeSignedMintTransaction,
    encodeSignedTransaction,
    encodeTransactionBatch,
    fromHex,
    signedTransactionBodyLength,
    toHex,
} from '../src/codec.ts';

// Golden fixtures generated by the Rust codec
// (crates/primitives/tests/wire_fixtures.rs). The Rust test asserts the file
// matches its codec; these tests assert this codec agrees with the file, so
// wire-format drift on either side fails CI instead of a browser session.
interface TransactionFixture {
    readonly kind: string;
    readonly signedHex: string;
    readonly bodyLength: number;
    readonly digestHex: string;
    readonly senderPublicKeyHex: string;
    readonly nonce: string;
    readonly toAccountKeyHex?: string;
    readonly value?: string;
}

interface WireFixture {
    readonly maxMintAmount: string;
    readonly batchHex: string;
    readonly transactions: readonly TransactionFixture[];
}

// Tests compile to dist-test/ before running, so resolve the fixture from
// the package root (npm test's working directory), not the compiled file.
const fixture: WireFixture = JSON.parse(
    readFileSync(join(process.cwd(), 'tests', 'fixtures', 'wire.json'), 'utf8'),
);

function entry(kind: string): TransactionFixture {
    const found = fixture.transactions.find((tx) => tx.kind === kind);
    assert.ok(found, `fixture covers a ${kind}`);
    return found;
}

// The scheme-tagged signature tail, for injecting into an encoder whose real
// signer is WebAuthn.
function signatureOf(tx: TransactionFixture): Uint8Array {
    return fromHex(tx.signedHex).slice(tx.bodyLength);
}

test('mint cap matches the Rust codec', () => {
    assert.equal(MAX_MINT_AMOUNT, BigInt(fixture.maxMintAmount));
});

test('every operation kind is present and its body length agrees', () => {
    assert.deepEqual(
        fixture.transactions.map((tx) => tx.kind).sort(),
        ['close_channel', 'mint', 'open_channel', 'timeout_channel', 'transfer'],
    );
    for (const tx of fixture.transactions) {
        assert.equal(
            signedTransactionBodyLength(fromHex(tx.signedHex)),
            tx.bodyLength,
            `${tx.kind} body length`,
        );
    }
});

test('transfer encoding is byte-identical to the Rust codec', async () => {
    const tx = entry('transfer');
    const encoded = await encodeSignedTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            toAccountKey: fromHex(tx.toAccountKeyHex ?? ''),
            value: BigInt(tx.value ?? ''),
            nonce: BigInt(tx.nonce),
        },
        async () => signatureOf(tx),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
    assert.equal(encoded.digestHex, tx.digestHex);
});

test('mint encoding is byte-identical to the Rust codec', async () => {
    const tx = entry('mint');
    const encoded = await encodeSignedMintTransaction(
        {
            senderPublicKey: fromHex(tx.senderPublicKeyHex),
            amount: BigInt(tx.value ?? ''),
            nonce: BigInt(tx.nonce),
        },
        async () => signatureOf(tx),
    );
    assert.equal(toHex(encoded.bytes), tx.signedHex);
    assert.equal(encoded.digestHex, tx.digestHex);
});

test('batch encoding is byte-identical to the Rust codec', () => {
    const batch = encodeTransactionBatch(
        fixture.transactions.map((tx) => fromHex(tx.signedHex)),
    );
    assert.equal(toHex(batch), fixture.batchHex);
});
